name: Black Formatting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  format:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
