# Based on GitHub action here: https://github.com/readthedocs/actions/tree/main/preview

name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  documentation-links:
    # Disabled until Read the Docs is setup
    if: false
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "{{ cookiecutter.project_slug|replace('.', '') }}"
