name: Build Template
on: [workflow_dispatch, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3
      with:
        path: 'cookiecutter-caf'

    - name: Run Cookiecutter
      uses: andrewthetechie/gha-cookiecutter@main
      with:
        template: 'cookiecutter-caf'
        cookiecutterValues: '{
            "caf": true,
            "project_name": "test"
          }'

    - name: Display Repo & Template Tree
      run: tree .

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd caf.test
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Formatting with Black
      run: |
        cd caf.test
        black src

    - name: Import Formatting (isort)
      run: |
        cd caf.test
        isort src

    - name: Lint with PyLint
      run: |
        cd caf.test
        pylint src

    - name: Lint with MyPy
      run: |
        cd caf.test
        mypy src

    - name: Lint with PyDocStyle
      run: |
        cd caf.test
        pydocstyle src

    - name: Dummy File Test
      run: touch caf.test/test.txt

    - name: Create Dummy PKG-INFO
      uses: 1arp/create-a-file-action@0.4.5
      with:
        path: 'caf.test'
        isAbsolutePath: false
        file: 'PKG-INFO'
        content: |
          Metadata-Version: 1.1
          Version: 0.1.0

    - name: Build Sphinx HTML Docs
      run: |
        cd caf.test/docs
        pip install -r requirements.txt
        sphinx-build source build/html -b html
